name: Firebase Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  VITE_APP_PORT: ${{ secrets.VITE_APP_PORT }}
  VITE_FB_API_KEY: ${{ secrets.VITE_FB_API_KEY }}
  VITE_FB_AUTH_DOMAIN: ${{ secrets.VITE_FB_AUTH_DOMAIN }}
  VITE_FB_PROJECT_ID: ${{ secrets.VITE_FB_PROJECT_ID }}
  VITE_FB_STORAGE_BUCKET: ${{ secrets.VITE_FB_STORAGE_BUCKET }}
  VITE_FB_MESSAGING_SENDER_ID: ${{ secrets.VITE_FB_MESSAGING_SENDER_ID }}
  VITE_FB_APP_ID: ${{ secrets.VITE_FB_APP_ID }}
  VITE_FB_MEASUREMENT_ID: ${{ secrets.VITE_FB_MEASUREMENT_ID }}
    
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install -g yarn

      - name: Update Firebase Config File
        run: |
          sed -i s/{{project-name}}/${{ env.VITE_FB_PROJECT_ID }}/g ./.firebaserc

      - name: yarn install, build and test
        run: |
          yarn install
          yarn build

      - name: Archive Build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: dist

  deploy:
    name: Deploy
    environment: prod
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download Build
        uses: actions/download-artifact@v2
        with:
          name: build
          path: dist
      - name: Depoy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
